routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function(){
    return view('home');
});

Auth::routes();

Route::get('/', [
    'as'    => 'index',
    'uses'  => 'HomeController@index'
]);

Route::get('gallery',[
    'as' => 'portfolio',
    'uses' => 'PortfolioController@index']);

Route::get('informations/{category?}', [
        'as' => 'category',
        'uses' => 'ArticlesController@index'
])->where('category','[\w-]+');

Route::get('services/', 'ServicesController@index')->name('services');
Route::get('services/{service}', [
    'as' => 'service',
    'uses' => 'ServicesController@show'
])->where('service','[\w-]+');

Route::post('service-form', 'ServicesController@store');
Route::post('page-form', 'PageController@store');
Route::post('detail-form', 'ServicesController@detailForm')->name('detailForm');

Route::get('page/{page}', 'PageController@page')->name('page');

Route::group(['middleware' => ['auth','admin'], 'prefix' => 'admin'], function(){
    Route::get('/', ['uses' => 'Admin\IndexController@index']);
    Route::resource('/informations', 'Admin\ArticlesController');
    Route::resource('/services', 'Admin\ServicesController');
    Route::resource('/accordion', 'Admin\AccordionController');
    Route::resource('/category', 'Admin\CategoryController');
    Route::resource('/gallery', 'Admin\PortfolioController');
    Route::resource('/page', 'Admin\PageController');
    Route::post('/update_file/{id}', 'Admin\PortfolioController@updateFileByID')->name('update_file');
    Route::post('/delete_selected', 'Admin\PortfolioController@delSelectedImages')->name('delete_selected');
    Route::resource('/menu', 'Admin\MenuController');
});

resources/views/alice/admin/layouts/accordionContent.blade.php
@if($accordions)
    @if(Session::has('status'))
        <div class="alert {{Session::get('class')}} alert-success">
            {{ Session::get('status')}}
        </div>
    @endif
    <div class="table-responsive my-4">
        <table class="table table-hover">
            <thead class="thead-light">
            <tr>
                <th class="align-left">ID</th>
                <th>Заголовок</th>
                <th>Опубликовано</th>
                <th>Услуга</th>
                <th>Действие</th>
            </tr>
            </thead>
            <tbody>
            @foreach($accordions as $accordion)
                <tr>
                    <td class="align-left">{{$accordion->id}}</td>
                    <td class="align-left">{!! link_to_route('accordion.edit', $accordion->title, ['accordion' => $accordion->id]) !!}</td>
                    <td class="align-left">
                        @if ($accordion->publish > 0)
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="check-circle" class="svg-inline--fa fa-check-circle fa-w-16 fa-2x" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path class="fa-w-16 fa-2x" d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"></path></svg>
                        @else
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="times-circle" class="svg-inline--fa fa-times-circle fa-w-16 fa-2x" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path class="fa-w-16 fa-2x" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm121.6 313.1c4.7 4.7 4.7 12.3 0 17L338 377.6c-4.7 4.7-12.3 4.7-17 0L256 312l-65.1 65.6c-4.7 4.7-12.3 4.7-17 0L134.4 338c-4.7-4.7-4.7-12.3 0-17l65.6-65-65.6-65.1c-4.7-4.7-4.7-12.3 0-17l39.6-39.6c4.7-4.7 12.3-4.7 17 0l65 65.7 65.1-65.6c4.7-4.7 12.3-4.7 17 0l39.6 39.6c4.7 4.7 4.7 12.3 0 17L312 256l65.6 65.1z"></path></svg>
                        @endif
                    </td>
                    <td>{{$accordion->service['title']}}</td>
                    <td>
                        {!! Form::open(['url' => route('accordion.destroy', ['accordion' => $accordion->id]), 'class'=>'form-horizontal','method'=>'POST']) !!}
                        @method('DELETE')
                        @csrf
                        {!! Form::button('Удалить', ['class' => 'btn btn-sm btn-danger', 'type'=>'submit']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    {!! link_to_route('accordion.create', 'Добавить материал', null,['class' => 'btn btn-primary']) !!}
@endif

resources/views/alice/admin/layouts/accordionCreate.blade.php
{!! Form::open(['url' => (isset($accordion->id)) ? route('accordion.update',['accordion' => $accordion->id]) : route('accordion.store'), 'class'=> 'contact-form my-4', 'method'=>'POST', 'enctype'=>'multipart/form-data']) !!}
    @if(isset($accordion->id))
        @method('PUT')
    @endif
    @csrf
    @if (Session::has('error'))
        <div class="alert alert-danger">
            @if (is_array(Session::get('error')))
                @foreach (Session::get('error') as $error)
                    {{ $error }}<br>
                @endforeach
            @else
                {{Session::get('error')}}
            @endif
        </div>
    @endif
    <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="title">Заголовок:</label>
                    {!! Form::text('title', isset($accordion->title) ? $accordion->title : Request::old('title'), ['class'=>'form-control', 'id' => 'title']) !!}
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="services">Услуга:</label>
                    {!! Form::select('service_id', $services, isset($accordion->service_id) ? $accordion->service_id : '', ['class'=>'form-control', 'id' => 'services', 'placeholder' => 'Услуги и цены']) !!}
                </div>
            </div>
        </div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <div class="custom-control mr-auto custom-checkbox">
                {{Form::hidden('publish', 0)}}
                {!! Form::checkbox('publish', isset($accordion->publish) ? $accordion->publish : 1, isset($accordion->publish) ? $accordion->publish : true , ['class' => 'custom-control-input check-input', 'id' => 'checkPublish'])!!}
                {!! Form::label('checkPublish', 'Опубликовать',['class' => 'custom-control-label']); !!}
            </div>
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label for="sort">Сортировка:</label>
            {!! Form::text('sort', isset($accordion->sort) ? $accordion->sort : Request::old('sort'), ['class'=>'form-control', 'id' => 'sort']) !!}
        </div>
    </div>
</div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="short-desc">Описание:</label>
                    {!! Form::textarea('desc', isset($accordion->desc) ? $accordion->desc : Request::old('desc'), ['id' => 'editor', 'class' => 'form-control', 'rows' => 4])!!}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group text-left">
                    {!! Form::button('Сохранить материал', ['class' => 'btn btn-primary', 'type'=>'submit']) !!}
                </div>
            </div>
        </div>
{!! Form::close() !!}
<script type="text/javascript">
    $(function(){
        $(document).on('change', 'input.check-input', function(){
            if ($(this).prop('checked')){
                $(this).val(1);
            } else {$(this).val(0);}
        });

        CKEDITOR.replace('editor', {
            allowedContent: true,
        });
    });
</script>

resources/views/alice/admin/layouts/articleCreate.blade.php
{!! Form::open(['url' => (isset($article->id)) ? route('informations.update',['informations' => $article->alias]) : route('informations.store'), 'class'=> 'contact-form my-4', 'method'=>'POST', 'enctype'=>'multipart/form-data']) !!}
    @if(isset($article->id))
        @method('PUT')
    @endif
    @csrf
    @if (Session::has('error'))
        <div class="alert alert-danger">
            @if (is_array(Session::get('error')))
                @foreach (Session::get('error') as $error)
                    {{ $error }}<br>
                @endforeach
            @else
                {{Session::get('error')}}
            @endif
        </div>
    @endif
    <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="title">Заголовок:</label>
                    {!! Form::text('title', isset($article->title) ? $article->title  : Request::old('title'), ['class'=>'form-control', 'id' => 'title']) !!}
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="alias">Псевдоним:</label>
                    {!! Form::text('alias', isset($article->alias) ? $article->alias : Request::old('alias'), ['class'=>'form-control', 'id' => 'alias']) !!}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="url">Url:</label>
                    {!! Form::text('url', isset($article->url) ? $article->url : Request::old('url'), ['class'=>'form-control', 'id' => 'url']) !!}
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="cat">Категория:</label>
                    <select name="category_id" class="form-control">{!! $categories !!}</select>
                </div>
            </div>
        </div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <div class="custom-control mr-auto custom-checkbox">
                {{Form::hidden('publish', 0)}}
                {!! Form::checkbox('publish', isset($article->publish) ? $article->publish : 1, isset($article->publish) ? $article->publish : true , ['class' => 'custom-control-input check-input', 'id' => 'checkPublish'])!!}
                {!! Form::label('checkPublish', 'Опубликовать',['class' => 'custom-control-label']); !!}
            </div>

        </div>
    </div>
</div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="short-desc">Краткое описание:</label>
                    {!! Form::textarea('desc', isset($article->desc) ? $article->desc : Request::old('desc'), ['id' => 'editor', 'class' => 'form-control', 'rows' => 4])!!}
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label for="text">Описание:</label>
                    {!! Form::textarea('text', isset($article->text) ? $article->text : Request::old('text'), ['id' => 'editor2', 'class' => 'form-control', 'rows' => 4])!!}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                @if(isset($article->image))
                    <div class="form-group">
                        <label>
                            Изображения материала:
                        </label>
                        <div class="image-wrapper">
                        {!! Html::image(Storage::url($article->image), "", ['class' => 'img-responsive img-thumbnail']) !!}
                        {!! Form::hidden('old_image', $article->image) !!}
                        </div>
                    </div>
                @endif
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="file">Загрузка изображения:</label>
                    <div class="custom-file">
                        {!! Form::file('file', ['id' => 'customFile', 'class' => 'custom-file-input'])!!}
                        {!! Form::label('file', 'Выберите файл', [ 'class'=>'custom-file-label', 'for' => 'customFile', 'data-browse' => 'Обзор'])!!}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group text-right">
                    {!! Form::button('Сохранить информацию', ['class' => 'btn btn-primary', 'type'=>'submit']) !!}
                </div>
            </div>
        </div>
{!! Form::close() !!}
<script type="text/javascript">
    $(function(){
        $('#customFile').on('change',function(e){
            var fileName = e.target.files[0].name;
            $(this).next('.custom-file-label').html(fileName);
        });

        $(document).on('change', 'input.check-input', function(){
            if ($(this).prop('checked')){
                $(this).val(1);
            } else {$(this).val(0);}
        });

        CKEDITOR.replace( 'editor', {
            allowedContent: true,
        });
        CKEDITOR.replace( 'editor2', {
            allowedContent: true,
        });
    });
</script>

resources/views/alice/admin/layouts/categoryContent.blade.php
@if($categories)
    @if(Session::has('status'))
        <div class="alert {{Session::get('class')}} alert-success">
            {{ Session::get('status')}}
        </div>
    @endif
    <div class="table-responsive my-4">
        <table class="table table-hover">
            <thead class="thead-light">
            <tr>
                <th class="align-left">ID</th>
                <th>Заголовок</th>
                <th>Опубликовано</th>
                <th>Родитель категории</th>
                <th>Изображение</th>
                <th>Действие</th>
            </tr>
            </thead>
            <tbody>
            @foreach($categories as $category)
                <tr>
                    <td class="align-left">{{$category->id}}</td>
                    <td class="align-left">{!! link_to_route('category.edit', $category->title, ['category' => $category->alias]) !!}</td>
                    <td class="align-left">
                        @if ($category->publish > 0)
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="check-circle" class="svg-inline--fa fa-check-circle fa-w-16 fa-2x" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path class="fa-w-16 fa-2x" d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"></path></svg>
                        @else
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="times-circle" class="svg-inline--fa fa-times-circle fa-w-16 fa-2x" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path class="fa-w-16 fa-2x" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm121.6 313.1c4.7 4.7 4.7 12.3 0 17L338 377.6c-4.7 4.7-12.3 4.7-17 0L256 312l-65.1 65.6c-4.7 4.7-12.3 4.7-17 0L134.4 338c-4.7-4.7-4.7-12.3 0-17l65.6-65-65.6-65.1c-4.7-4.7-4.7-12.3 0-17l39.6-39.6c4.7-4.7 12.3-4.7 17 0l65 65.7 65.1-65.6c4.7-4.7 12.3-4.7 17 0l39.6 39.6c4.7 4.7 4.7 12.3 0 17L312 256l65.6 65.1z"></path></svg>
                        @endif
                    </td>
                    <td>{{$category->parent['title']}}</td>
                    <td>
                        @if(isset($category->image))
                            {!! Html::image(Storage::url($category->image), "", ['class' => 'img-responsive img-thumbnail']) !!}
                        @endif
                    </td>
                    <td>
                        {!! Form::open(['url' => route('category.destroy', ['category' => $category->alias]), 'class'=>'form-horizontal','method'=>'POST']) !!}
                        @method('DELETE')
                        @csrf
                        {!! Form::button('Удалить', ['class' => 'btn btn-sm btn-danger', 'type'=>'submit']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    {!! link_to_route('category.create', 'Добавить категорию', null,['class' => 'btn btn-primary']) !!}

@endif

resources/views/alice/admin/layouts/menuContent.blade.php
@if($menus)
    @if(Session::has('status'))
        <div class="alert {{Session::get('class')}} alert-success">
            {{ Session::get('status')}}
        </div>
    @endif
    <div class="table-responsive my-4">
        <table class="table table-hover">
            <thead class="thead-light">
            <tr>
                <th class="align-left">ID</th>
                <th>Заголовок</th>
                <th>Опубликовано</th>
                <th>URL</th>
                <th>Действие</th>
            </tr>
            </thead>
            <tbody>
            @foreach($menus as $menu)
                <tr>
                    <td class="align-left">{{$menu->id}}</td>
                    <td class="align-left">{!! link_to_route('menu.edit', $menu->title, ['menu' => $menu->id]) !!}</td>
                    <td class="align-left">
                        @if ($menu->publish > 0)
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="check-circle" class="svg-inline--fa fa-check-circle fa-w-16 fa-2x" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path class="fa-w-16 fa-2x" d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"></path></svg>
                        @else
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="times-circle" class="svg-inline--fa fa-times-circle fa-w-16 fa-2x" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path class="fa-w-16 fa-2x" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm121.6 313.1c4.7 4.7 4.7 12.3 0 17L338 377.6c-4.7 4.7-12.3 4.7-17 0L256 312l-65.1 65.6c-4.7 4.7-12.3 4.7-17 0L134.4 338c-4.7-4.7-4.7-12.3 0-17l65.6-65-65.6-65.1c-4.7-4.7-4.7-12.3 0-17l39.6-39.6c4.7-4.7 12.3-4.7 17 0l65 65.7 65.1-65.6c4.7-4.7 12.3-4.7 17 0l39.6 39.6c4.7 4.7 4.7 12.3 0 17L312 256l65.6 65.1z"></path></svg>
                        @endif
                    </td>
                    <td>{{$menu->url}}</td>
                    <td>
                        {!! Form::open(['url' => route('menu.destroy', ['menu' => $menu->id]), 'class'=>'form-horizontal','method'=>'POST']) !!}
                        @method('DELETE')
                        @csrf
                        {!! Form::button('Удалить', ['class' => 'btn btn-sm btn-danger', 'type'=>'submit']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    {!! link_to_route('menu.create', 'Добавить пункт', null,['class' => 'btn btn-primary']) !!}

@endif

resources/views/alice/admin/layouts/navigation.blade.php
@if($adminNav)
    <ul class="navbar-nav mr-auto">
        @foreach($adminNav->items as $key => $menuItem)
            @if (!$menuItem->hasParent())
                <li class="nav-item {{ (URL::current() == $menuItem->url()) ? 'active' : '' }} {{($menuItem->hasChildren()?"dropdown":'')}}">
                    <a class="nav-link {{($menuItem->hasChildren()?"dropdown-toggle":'')}}" href="{{$menuItem->url()}}" {{($menuItem->hasChildren()? 'id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"':'')}}>{!!  $menuItem->title !!}</a>
            @endif
            @if ($menuItem->hasChildren())
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    @foreach($menuItem->children() as $subMenuItem)
                        <a class="dropdown-item" href="{{$subMenuItem->url() }}">{!! $subMenuItem->title !!}</a>
                    @endforeach
                </div>
                </li>
            @else
                </li>
            @endif
        @endforeach
    </ul>
@endif

resources/views/alice/admin/layouts/pageContent.blade.php
@if($pages)
    @if(Session::has('status'))
        <div class="alert {{Session::get('class')}} alert-success">
            {{ Session::get('status')}}
        </div>
    @endif
    <div class="table-responsive my-4">
        <table class="table table-hover">
            <thead class="thead-light">
            <tr>
                <th class="align-left">ID</th>
                <th>Заголовок</th>
                <th>Опубликовано</th>
                <th>Псевдоним</th>
                <th>Действие</th>
            </tr>
            </thead>
            <tbody>
            @foreach($pages as $page)
                <tr>
                    <td class="align-left">{{$page->id}}</td>
                    <td class="align-left">{!! link_to_route('page.edit', $page->title, ['page' => $page->alias]) !!}</td>
                    <td class="align-left">
                        @if ($page->publish > 0)
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="check-circle" class="svg-inline--fa fa-check-circle fa-w-16 fa-2x" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path class="fa-w-16 fa-2x" d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"></path></svg>
                        @else
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="times-circle" class="svg-inline--fa fa-times-circle fa-w-16 fa-2x" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path class="fa-w-16 fa-2x" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm121.6 313.1c4.7 4.7 4.7 12.3 0 17L338 377.6c-4.7 4.7-12.3 4.7-17 0L256 312l-65.1 65.6c-4.7 4.7-12.3 4.7-17 0L134.4 338c-4.7-4.7-4.7-12.3 0-17l65.6-65-65.6-65.1c-4.7-4.7-4.7-12.3 0-17l39.6-39.6c4.7-4.7 12.3-4.7 17 0l65 65.7 65.1-65.6c4.7-4.7 12.3-4.7 17 0l39.6 39.6c4.7 4.7 4.7 12.3 0 17L312 256l65.6 65.1z"></path></svg>
                        @endif
                    </td>
                    <td>{{$page->alias}}</td>
                    <td>
                        {!! Form::open(['url' => route('page.destroy', ['page' => $page->alias]), 'class'=>'form-horizontal','method'=>'POST']) !!}
                        @method('DELETE')
                        @csrf
                        {!! Form::button('Удалить', ['class' => 'btn btn-sm btn-danger', 'type'=>'submit']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    {!! link_to_route('page.create', 'Добавить страницу', null,['class' => 'btn btn-primary']) !!}
@endif

resources/views/alice/admin/layouts/servicesContent.blade.php
@if($services)
    @if(Session::has('status'))
        <div class="alert {{Session::get('class')}} alert-success">
            {{ Session::get('status')}}
        </div>
    @endif
    <div class="table-responsive my-4">
        <table class="table table-hover">
            <thead class="thead-light">
            <tr>
                <th class="align-left">ID</th>
                <th>Заголовок</th>
                <th>Опубликовано</th>
                <th>Изображение</th>
                <th>Псевдоним</th>
                <th>Действие</th>
            </tr>
            </thead>
            <tbody>
            @foreach($services as $service)
                <tr>
                    <td class="align-left">{{$service->id}}</td>
                    <td class="align-left">{!! link_to_route('services.edit', $service->title, ['services' => $service->alias]) !!}</td>
                    <td class="align-left">
                        @if ($service->publish > 0)
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="check-circle" class="svg-inline--fa fa-check-circle fa-w-16 fa-2x" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path class="fa-w-16 fa-2x" d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"></path></svg>
                        @else
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="times-circle" class="svg-inline--fa fa-times-circle fa-w-16 fa-2x" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path class="fa-w-16 fa-2x" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm121.6 313.1c4.7 4.7 4.7 12.3 0 17L338 377.6c-4.7 4.7-12.3 4.7-17 0L256 312l-65.1 65.6c-4.7 4.7-12.3 4.7-17 0L134.4 338c-4.7-4.7-4.7-12.3 0-17l65.6-65-65.6-65.1c-4.7-4.7-4.7-12.3 0-17l39.6-39.6c4.7-4.7 12.3-4.7 17 0l65 65.7 65.1-65.6c4.7-4.7 12.3-4.7 17 0l39.6 39.6c4.7 4.7 4.7 12.3 0 17L312 256l65.6 65.1z"></path></svg>
                        @endif
                    </td>
                    <td>
                        @if(isset($service->image))
                            {!! Html::image(Storage::url($service->image), "", ['class' => 'img-responsive img-thumbnail']) !!}
                        @endif
                    </td>
                    <td>{{$service->alias}}</td>
                    <td>
                        {!! Form::open(['url' => route('services.destroy', ['services' => $service->alias]), 'class'=>'form-horizontal','method'=>'POST']) !!}
                        @method('DELETE')
                        @csrf
                        {!! Form::button('Удалить', ['class' => 'btn btn-sm btn-danger', 'type'=>'submit']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    {!! link_to_route('services.create', 'Добавить услугу', null,['class' => 'btn btn-primary']) !!}
@endif